# Project Information
site_name: MNX Solutions Incident Response Documentation
site_description: A collection of information about the MNX Solutions incident response process. Not only how to prepare new employees for on-call responsibilities, but also how to handle major incidents, both in preparation and after-work.
config.site_author: MNX Solutions, LLC.
site_favicon: 'assets/img/icon.png'
config.site_url: https://response.mnxsolutions.com

# Repository
config.repo_name: 'GitHub'
config.repo_url: https://github.com/mnx-solutions/incident-response-docs

# Copyright
config.copyright: 'Copyright &copy; 2017 MNX Solutions, LLC.'

# Theme
theme: 'material'
theme_dir: 'theme'
extra_css: ['assets/css/extra.css']
extra:
  logo: 'assets/img/icon.png'
  cover: 'assets/img/cover.png'
  palette:
    primary: 'green'
    accent: 'blue grey'
  font:
    text: 'Colfax Regular'
    code: 'Roboto Mono'
  author:
    github: 'mnx-solutions'
    twitter: 'MNXSolutions'

# Contents
pages:
  - Home: 'index.md'
  - On-Call:
    - Being On-Call: 'oncall/being_oncall.md'
    - Alerting Principles: 'oncall/alerting_principles.md'
  - Before an Incident:
    - What is an Incident?: 'before/what_is_an_incident.md'
    - Severity Levels: 'before/severity_levels.md'
    - Different Roles: 'before/different_roles.md'
    - Call Etiquette: 'before/call_etiquette.md'
    - Complex Incidents: 'before/complex_incidents.md'
  - During an Incident:
    - During an Incident: 'during/during_an_incident.md'
    - Security Incident: 'during/security_incident_response.md'
  - After an Incident:
    - After an Incident: 'after/after_an_incident.md'
    - Post-Mortem Process: 'after/post_mortem_process.md'
    - Post-Mortem Template: 'after/post_mortem_template.md'
  - Training:
    - Overview: 'training/overview.md'
    - Incident Commander: 'training/incident_commander.md'
    - Deputy: 'training/deputy.md'
    - Scribe: 'training/scribe.md'
    - Subject Matter Expert: 'training/subject_matter_expert.md'
    - Customer Liaison: 'training/customer_liaison.md'
    - Glossary: 'training/glossary.md'
  - Additional Resources:
    - Reading: 'resources/reading.md'
    - ChatOps: 'resources/chatops.md'
  - About: 'about.md'

# Analytics
#google_analytics: ['UA-8759953-1', 'auto']

# Extensions
markdown_extensions:
  - page.toc(permalink=#)
  - sane_lists:
  - admonition:
